### ISSUE TITLE
mis-shaped results

### ISSUE THREAD

**Issue by manlyman29** [oslllo/svg-fixer#107]
I used this library to correct svg fill rule and make it ready to be converted to a typeface without filling the strokes.
Although it seems to have fixed the fill rule issue, the results seem mis-shaped as can be seen below:
![Screenshot 2024-05-22 at 11 12 27](https://github.com/oslllo/svg-fixer/assets/63221039/750cdec7-2ec8-4432-bc21-d065c6ba802a)

It draws the less complex ones correctly but with some added complexity like these two icons, it draws additional shapes.

The icons I used as input were from popular icon pack https://ionic.io/ionicons which I assumes rules out the improper input format possibility.

**Comment by Ghustavh97** [comment]
Hi, thanks for the issue.

1. The resolution for the image you provided is too low and I cannot see exactly what's going on. A side by side comparison with what the expected icon should look like would be great too.
2. I need reproduction code, mainly what code, icons and steps you used to get the results so I can try them out on my side.
3. Try to increase and play around with `traceResolution` in the options object parameter, maybe that will fix the issue. The default traceResolution is `600`.

```js 
SVGFixer('directory/containing/svgs', 'directory/to-store/fixed-svgs', { traceResolution: 1200 });
```

**Comment by manlyman29** [comment]
@Ghustavh97 I appreciate the response,
I tried the traceResolution but it resulted the same, this is side-by-side of the expected and actual result:

![compare](https://github.com/oslllo/svg-fixer/assets/63221039/54d384f3-3b9a-4f80-82ee-aeb7ae4df5cd)

And regarding the reproduction steps you can use below svg:
![people-outline](https://github.com/oslllo/svg-fixer/assets/63221039/406f3e92-f305-4dd4-a740-527d93460ba8)

I used the CLI command:
`oslllo-svg-fixer -d ./ -s ./ --tr 1200`
And then I used flutter_icon_generator to generate the font. The culprit here could very well be the flutter_icon_generator as well. I will dig more onto this tomorrow. On first efforts I tried enabling and disabling ignore_shapes option but that didn't generate a proper result either. I also attached the svg I had problems with
![people-outline](https://github.com/oslllo/svg-fixer/assets/63221039/a24801aa-bfd5-40a7-8bb3-82eed51a409b)

**Comment by Ghustavh97** [comment]
Try to convert the icons using https://fontello.com/ and see if you get the same issues.

**Comment by manlyman29** [comment]
@Ghustavh97 fontello gives below error:
`If image looks not as expected please convert to compound path manually. See [wiki](https://github.com/fontello/fontello/wiki/How-to-use-custom-images#importing-svg-images).

Skipped tags and attributes: stroke,fill-rule,fill`

**Comment by manlyman29** [comment]
icomoon.io worked and it has a flutter class generator too. Thanks for the amazing work here.

**Comment by Ghustavh97** [comment]
No problem. Thanks for posting the links and info to your solution.
