### ISSUE TITLE
Doc page domain expired. Want to know how to install this package.

### ISSUE THREAD

**Issue by vanleefxp** [oslllo/svg-fixer#116]
When I clicked the documentation page the document didn't show up. Instead, there is a page saying that the domain has expired. I wonder how can I install this package since I tried `pnpm install svg-fixer` but there is error saying that this package cannot be found.

```
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/svg-fixer: Not Found - 404
```

**Comment by Ghustavh97** [comment]
https://docs-oslllo-com.onrender.com/svg-fixer/master
