### ISSUE TITLE
Cant install from npm due to canvas

### ISSUE THREAD

**Issue by CodeByAlex** [oslllo/svg-fixer#2]
I want to use this package badly because I'm having the same issue it tries to resolve but I cant download it because I cant install canvas using node 12. How are you able to install?

**Comment by Ghustavh97** [comment]
@CodeByAlex hi, what is the error message?

**Comment by CodeByAlex** [comment]
Hey @Ghustavh97 - this is the error I'm seeing:
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.6.1 install script.

**Comment by Ghustavh97** [comment]
@CodeByAlex try `npm i node-pre-gyp` then reinstalling the package again.

**Comment by CodeByAlex** [comment]
Its unfortunately still giving errors:
Failed to execute '/usr/local/Cellar/node@12/12.16.1/bin/node /usr/local/Cellar/node@12/12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=...../node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=...../Style/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)

Ive tried what you suggested, removing node modules, removing package lock, and installed canvas specifically. Nothing seems to work. Im assuming it works for you - what version of node/npm are you using? Do you have any other suggestions?

**Comment by Ghustavh97** [comment]
@CodeByAlex 

My local machine:
OS: `Ubuntu 18.04.4 LTS`
node : `v12.16.1`
npm: `6.14.4`

I have also added an osx test build and it seems to be passing. [Here](https://travis-ci.org/github/oslllo/svg-fixer/jobs/686696370). its running: 

OS: `mac os 10.15.4`
node:  `v12.16.3`
npm: `6.14.4`
nvm  :`0.35.3`

Have you also tried installing `node-pre-gyp` globally? `npm i node-pre-gyp -g`

**Comment by Ghustavh97** [comment]
Some more suggestions:
- [Try `yarn` instead of `npm`](https://github.com/mapbox/node-pre-gyp/issues/367#issuecomment-447676163)
- [This](https://github.com/Automattic/node-canvas/issues/1475#issuecomment-536098104)
- [Could be a network issue](https://github.com/mapbox/node-pre-gyp/issues/367#issuecomment-408664943)

**Comment by Ghustavh97** [comment]
@CodeByAlex so I think I managed to reproduce your error
```shell
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/www/html/test-npm/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/var/www/html/test-npm/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN test-npm@1.0.0 No description
npm WARN test-npm@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.6.1 install script.
```

This is after I tricked my network drivers by pointing them to `localhost`. im 99% sure its a network issue.

Would be nice if you could provide the full error log as well so that I could confirm this.

**Comment by CodeByAlex** [comment]
My apologies - this was a network issue. Thanks for looking into this
